using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
//using Robust.Shared.Utility;

namespace Content.Client.Cult.Commune.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class CultCommuneWindow : DefaultWindow
    {
        public CultCommuneWindow()
        {
            RobustXamlLoader.Load(this);
        }
        /*
        public void Populate(SharedCultCommuneComponent.CultCommuneUserInterfaceState state)
        {
            if (state.Mode == SharedPaperComponent.PaperAction.Write)
            {
                Input.Visible = true;
            }
            var msg = new FormattedMessage();
            msg.AddMarkupPermissive(state.Text);
            Label.SetMessage(msg);
			
        }
        */
    }
}
